site_name: Depalletization agent ROSE-AP
repo_url: https://github.com/itti-pl/depalletization-agent-rose-ap.git
site_description: Depalletization agent ROSE-AP Documentation
site_dir: html
use_directory_urls: false
theme: readthedocs
nav:
  - User & Programmers Manual:
    - Architecture : 'docs/architecture.md'
    - API : 'docs/api.md'
    - User Guide: 'docs/usermanual.md'
    - Contribution Guidelines: 'docs/contributing.md'
  - Installation & Administration Manual: 
    - Installation Guide: 'docs/installationguide.md'
    - Step by step Guide: 'docs/stepbystepguide.md'
    - Building docker image Guide: 'docs/dockerguide.md'